## Aufgabe 30 Methode der kleinsten Quadrate

In [1]:
import numpy as np
import matplotlib.pyplot as plt

### a) Designmatrix A

In [2]:
psi = np.arange(0,331,30) # in degree
asym = [-0.032,0.010,0.057,
        0.068,0.076,0.080,
        0.031,0.005,-0.041,
        -0.090,-0.088,-0.074]
asym = np.array(asym)
asym_err = 0.011

psi.shape, asym.shape

((12,), (12,))

In [3]:
psi = np.radians(psi)

psi

array([0.        , 0.52359878, 1.04719755, 1.57079633, 2.0943951 ,
       2.61799388, 3.14159265, 3.66519143, 4.1887902 , 4.71238898,
       5.23598776, 5.75958653])

In [4]:
# design matrix:
A = np.column_stack([np.cos(psi),np.sin(psi)])

A.shape, A

((12, 2),
 array([[ 1.00000000e+00,  0.00000000e+00],
        [ 8.66025404e-01,  5.00000000e-01],
        [ 5.00000000e-01,  8.66025404e-01],
        [ 6.12323400e-17,  1.00000000e+00],
        [-5.00000000e-01,  8.66025404e-01],
        [-8.66025404e-01,  5.00000000e-01],
        [-1.00000000e+00,  1.22464680e-16],
        [-8.66025404e-01, -5.00000000e-01],
        [-5.00000000e-01, -8.66025404e-01],
        [-1.83697020e-16, -1.00000000e+00],
        [ 5.00000000e-01, -8.66025404e-01],
        [ 8.66025404e-01, -5.00000000e-01]]))

### b) Lösungsvektor $\hat{\vec{a}}$

$\hat{\vec{a}} = (A^T A)^{-1} A^T \vec{y}$

In [5]:
y = asym

In [6]:
a = np.linalg.inv(A.T @ A) @ A.T @ y

a

array([-0.0375063 ,  0.07739978])

### c) Kovarianzmatrix  $V[\hat{\vec{a}}]$
$V[\vec{y}] = \sigma^2 \mathbb{1}$  
$V[\hat{\vec{a}}] = \sigma^2 (A^T A)^{-1}$

In [7]:
sigma = asym_err

In [8]:
# Kovarianzmatrix:
V_a = sigma**2 * np.linalg.inv(A.T @ A) 

V_a

array([[ 2.01666667e-05, -1.67921232e-21],
       [-1.67921232e-21,  2.01666667e-05]])

In [9]:
# Fehler von a:
a_err = np.sqrt(np.diag(V_a)) 
# Korrelationskoeffizient:
rho = V_a[1,0] / a_err[0]**2 

a_err, rho

(array([0.00449073, 0.00449073]), -8.326672684688675e-17)

### d) $A_0$ und $\delta$ aus $a_1$ und $a_2$ mit Fehler und Korrelation

$f(\Psi) = A_0 \cos(\Psi + \delta) = a_1 \cos(\Psi) + a_2 \sin(\Psi)$  
siehe OneNote für folgendes:  
$A_0 = \frac{a_1}{\cos(\arctan(-a_2/a_1))}$  
$\delta = \arctan(-a_2/a_1)$   

$V\left[\begin{pmatrix}A_0 \\ \delta \end{pmatrix}\right] = J \cdot V[\hat{\vec{a}}] \cdot J^T$  
mit $J = 
\begin{pmatrix} 
    \left( \frac{a_2^2}{a_1^2} + 1 \right)^{-1/2} &
    \frac{a_2}{a_1}\left( \frac{a_2^2}{a_1^2} + 1 \right)^{-1/2} \\
    \frac{a_2}{a_1^2+a_2^2} & -\frac{a_1}{a_1^2+a_2^2}
\end{pmatrix}$

In [10]:
# A_0 und delta:
a1 = a[0]
a2 = a[1]
A_0 = a1 / np.cos(np.arctan(-a2/a1))
delta = np.arctan(-a2/a1)

A_0, delta

(-0.0860084162956094, 1.1195615399310932)

In [11]:
# Jacobi-Matrix:
J = [[(a2**2/a1**2+1)**-(1/2), (a2/a1)*(a2**2/a1**2+1)**-(1/2)],
     [a2/(a1**2+a2**2), -a1/(a1**2+a2**2)]]
J = np.array(J)

J

array([[ 0.43607706, -0.89990933],
       [10.46303798,  5.07016733]])

In [12]:
# Kovarianzmatrix:
V = J @ V_a @ J.T

V

array([[2.01666667e-05, 2.71050543e-20],
       [1.35525272e-20, 2.72616550e-03]])